name: Add Contributors

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  add-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add contributors
      uses: allcontributors/add-contributors@v1
      with:
        contributors: "user1,user2,user3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
