name: Update Contributors

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Contributors List
      run: |
        git log --format='%aN <%aE>' | sort -u > CONTRIBUTORS.md

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CONTRIBUTORS.md
        git commit -m "Update CONTRIBUTORS.md"
        git push
